version: '3'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
     - ./database:/var/lib/mysql
  webapp:
    image: ghcr.io/glpi-project/glpi-nightly:master
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./forensic_log:/var/log/httpd/forensic_log
      - ./webapp:/var/www
    depends_on:
      - db
